var DeviceLayr;(function(DeviceLayr_1){"use strict";(function(AxisStatus){AxisStatus[AxisStatus["negative"]=0]="negative";AxisStatus[AxisStatus["neutral"]=1]="neutral";AxisStatus[AxisStatus["positive"]=2]="positive";})(DeviceLayr_1.AxisStatus||(DeviceLayr_1.AxisStatus={}));var AxisStatus=DeviceLayr_1.AxisStatus;var DeviceLayr=(function(){function DeviceLayr(settings){this.InputWritr=settings.InputWriter;this.triggers=settings.triggers;this.aliases=settings.aliases;this.gamepads=[];}
DeviceLayr.prototype.getInputWritr=function(){return this.InputWritr;};DeviceLayr.prototype.getTriggers=function(){return this.triggers;};DeviceLayr.prototype.getAliases=function(){return this.aliases;};DeviceLayr.prototype.getGamepads=function(){return this.gamepads;};DeviceLayr.prototype.checkNavigatorGamepads=function(){if(typeof navigator.getGamepads==="undefined"||!navigator.getGamepads()[this.gamepads.length]){return 0;}
this.registerGamepad(navigator.getGamepads()[this.gamepads.length]);return this.checkNavigatorGamepads()+1;};DeviceLayr.prototype.registerGamepad=function(gamepad){this.gamepads.push(gamepad);this.setDefaultTriggerStatuses(gamepad,this.triggers);};DeviceLayr.prototype.activateAllGamepadTriggers=function(){for(var i=0;i<this.gamepads.length;i+=1){this.activateGamepadTriggers(this.gamepads[i]);}};DeviceLayr.prototype.activateGamepadTriggers=function(gamepad){var mapping=DeviceLayr.controllerMappings[gamepad.mapping||"standard"],i;for(i=0;i<mapping.axes.length;i+=1){this.activateAxisTrigger(gamepad,mapping.axes[i].name,mapping.axes[i].axis,gamepad.axes[i]);}
for(i=0;i<mapping.buttons.length;i+=1){this.activateButtonTrigger(gamepad,mapping.buttons[i],gamepad.buttons[i].pressed);}};DeviceLayr.prototype.activateAxisTrigger=function(gamepad,name,axis,magnitude){var listing=this.triggers[name][axis],status;if(!listing){return;}
status=this.getAxisStatus(gamepad,magnitude);if(listing.status===status){return false;}
if(listing.status!==undefined&&listing[AxisStatus[listing.status]]!==undefined){this.InputWritr.callEvent(this.aliases.off,listing[AxisStatus[listing.status]]);}
listing.status=status;if(listing[AxisStatus[status]]!==undefined){this.InputWritr.callEvent(this.aliases.on,listing[AxisStatus[status]]);}
return true;};DeviceLayr.prototype.activateButtonTrigger=function(gamepad,name,status){var listing=this.triggers[name];if(!listing||listing.status===status){return false;}
listing.status=status;this.InputWritr.callEvent(status?this.aliases.on:this.aliases.off,listing.trigger);return true;};DeviceLayr.prototype.clearAllGamepadTriggers=function(){for(var i=0;i<this.gamepads.length;i+=1){this.clearGamepadTriggers(this.gamepads[i]);}};DeviceLayr.prototype.clearGamepadTriggers=function(gamepad){var mapping=DeviceLayr.controllerMappings[gamepad.mapping||"standard"],i;for(i=0;i<mapping.axes.length;i+=1){this.clearAxisTrigger(gamepad,mapping.axes[i].name,mapping.axes[i].axis);}
for(i=0;i<mapping.buttons.length;i+=1){this.clearButtonTrigger(gamepad,mapping.buttons[i]);}};DeviceLayr.prototype.clearAxisTrigger=function(gamepad,name,axis){var listing=this.triggers[name][axis];listing.status=AxisStatus.neutral;};DeviceLayr.prototype.clearButtonTrigger=function(gamepad,name){var listing=this.triggers[name];listing.status=false;};DeviceLayr.prototype.setDefaultTriggerStatuses=function(gamepad,triggers){if(triggers===void 0){triggers=this.triggers;}
var mapping=DeviceLayr.controllerMappings[gamepad.mapping||"standard"],button,joystick,i,j;for(i=0;i<mapping.buttons.length;i+=1){button=triggers[mapping.buttons[i]];if(button&&button.status===undefined){button.status=false;}}
for(i=0;i<mapping.axes.length;i+=1){joystick=triggers[mapping.axes[i].name];for(j in joystick){if(!joystick.hasOwnProperty(j)){continue;}
if(joystick[j].status===undefined){joystick[j].status=AxisStatus.neutral;}}}};DeviceLayr.prototype.getAxisStatus=function(gamepad,magnitude){var joystickThreshold=DeviceLayr.controllerMappings[gamepad.mapping||"standard"].joystickThreshold;if(magnitude>joystickThreshold){return AxisStatus.positive;}
if(magnitude<-joystickThreshold){return AxisStatus.negative;}
return AxisStatus.neutral;};DeviceLayr.controllerMappings={"standard":{"axes":[{"axis":"x","joystick":0,"name":"leftJoystick"},{"axis":"y","joystick":0,"name":"leftJoystick"},{"axis":"x","joystick":1,"name":"rightJoystick"},{"axis":"y","joystick":1,"name":"rightJoystick"}],"buttons":["a","b","x","y","leftTop","rightTop","leftTrigger","rightTrigger","select","start","leftStick","rightStick","dpadUp","dpadDown","dpadLeft","dpadRight"],"joystickThreshold":.49}};return DeviceLayr;})();DeviceLayr_1.DeviceLayr=DeviceLayr;})(DeviceLayr||(DeviceLayr={}));