var EightBittr;(function(EightBittr_1){"use strict";var EightBittr=(function(){function EightBittr(settings){if(settings===void 0){settings={};}
var EightBitter=EightBittr.prototype.ensureCorrectCaller(this),constants=settings.constants,constantsSource=settings.constantsSource||EightBitter,i;EightBitter.unitsize=settings.unitsize||1;EightBitter.constants=constants;if(constants){for(i=0;i<constants.length;i+=1){EightBitter[constants[i]]=constantsSource[constants[i]];}}}
EightBittr.prototype.reset=function(EightBitter,resets,customs){var reset,i;EightBitter.customs=customs;for(i=0;i<resets.length;i+=1){reset=resets[i];if(!EightBitter[reset]){throw new Error(reset+" is missing on a resetting EightBittr.");}
EightBitter[reset](EightBitter,customs);}};EightBittr.prototype.resetTimed=function(EightBitter,resets,customs){var timeStartTotal=performance.now(),timeEndTotal,timeStart,timeEnd,i;this.resetTimes={order:resets,times:[]};for(i=0;i<resets.length;i+=1){timeStart=performance.now();EightBitter[resets[i]](EightBitter,customs);timeEnd=performance.now();this.resetTimes.times.push({"name":resets[i],"timeStart":timeStart,"timeEnd":timeEnd,"timeTaken":timeEnd-timeStart});}
timeEndTotal=performance.now();this.resetTimes.total={"name":"resetTimed","timeStart":timeStartTotal,"timeEnd":timeEndTotal,"timeTaken":timeEndTotal-timeStartTotal};};EightBittr.prototype.createCanvas=function(width,height,scaling){if(scaling===void 0){scaling=1;}
var canvas=document.createElement("canvas"),context=canvas.getContext("2d");canvas.width=width;canvas.height=height;scaling=scaling||1;canvas.style.width=(width*scaling)+"px";canvas.style.height=(height*scaling)+"px";if(typeof context.imageSmoothingEnabled!=="undefined"){context.imageSmoothingEnabled=false;}
else if(typeof context.webkitImageSmoothingEnabled!=="undefined"){context.webkitImageSmoothingEnabled=false;}
else if(typeof context.mozImageSmoothingEnabled!=="undefined"){context.mozImageSmoothingEnabled=false;}
else if(typeof context.msImageSmoothingEnabled!=="undefined"){context.msImageSmoothingEnabled=false;}
else if(typeof context.oImageSmoothingEnabled!=="undefined"){context.oImageSmoothingEnabled=false;}
return canvas;};EightBittr.prototype.shiftVert=function(thing,dy){thing.top+=dy;thing.bottom+=dy;};EightBittr.prototype.shiftHoriz=function(thing,dx){thing.left+=dx;thing.right+=dx;};EightBittr.prototype.setTop=function(thing,top){thing.top=top;thing.bottom=thing.top+thing.height*thing.EightBitter.unitsize;};EightBittr.prototype.setRight=function(thing,right){thing.right=right;thing.left=thing.right-thing.width*thing.EightBitter.unitsize;};EightBittr.prototype.setBottom=function(thing,bottom){thing.bottom=bottom;thing.top=thing.bottom-thing.height*thing.EightBitter.unitsize;};EightBittr.prototype.setLeft=function(thing,left){thing.left=left;thing.right=thing.left+thing.width*thing.EightBitter.unitsize;};EightBittr.prototype.setMidX=function(thing,x){thing.EightBitter.setLeft(thing,x-thing.width*thing.EightBitter.unitsize/2);};EightBittr.prototype.setMidY=function(thing,y){thing.EightBitter.setTop(thing,y-thing.height*thing.EightBitter.unitsize/2);};EightBittr.prototype.setMid=function(thing,x,y){thing.EightBitter.setMidX(thing,x);thing.EightBitter.setMidY(thing,y);};EightBittr.prototype.getMidX=function(thing){return thing.left+thing.width*thing.EightBitter.unitsize/2;};EightBittr.prototype.getMidY=function(thing){return thing.top+thing.height*thing.EightBitter.unitsize/2;};EightBittr.prototype.setMidObj=function(thing,other){thing.EightBitter.setMidXObj(thing,other);thing.EightBitter.setMidYObj(thing,other);};EightBittr.prototype.setMidXObj=function(thing,other){thing.EightBitter.setLeft(thing,thing.EightBitter.getMidX(other)
-(thing.width*thing.EightBitter.unitsize/2));};EightBittr.prototype.setMidYObj=function(thing,other){thing.EightBitter.setTop(thing,thing.EightBitter.getMidY(other)
-(thing.height*thing.EightBitter.unitsize/2));};EightBittr.prototype.objectToLeft=function(thing,other){return(thing.EightBitter.getMidX(thing)<thing.EightBitter.getMidX(other));};EightBittr.prototype.updateTop=function(thing,dy){thing.top+=dy||0;thing.bottom=thing.top+thing.height*thing.EightBitter.unitsize;};EightBittr.prototype.updateRight=function(thing,dx){thing.right+=dx||0;thing.left=thing.right-thing.width*thing.EightBitter.unitsize;};EightBittr.prototype.updateBottom=function(thing,dy){thing.bottom+=dy||0;thing.top=thing.bottom-thing.height*thing.EightBitter.unitsize;};EightBittr.prototype.updateLeft=function(thing,dx){thing.left+=dx||0;thing.right=thing.left+thing.width*thing.EightBitter.unitsize;};EightBittr.prototype.slideToX=function(thing,x,maxDistance){var midx=thing.EightBitter.getMidX(thing);maxDistance=maxDistance||Infinity;if(midx<x){thing.EightBitter.shiftHoriz(thing,Math.min(maxDistance,x-midx));}
else{thing.EightBitter.shiftHoriz(thing,Math.max(-maxDistance,x-midx));}};EightBittr.prototype.slideToY=function(thing,y,maxDistance){var midy=thing.EightBitter.getMidY(thing);maxDistance=maxDistance||Infinity;if(midy<y){thing.EightBitter.shiftVert(thing,Math.min(maxDistance,y-midy));}
else{thing.EightBitter.shiftVert(thing,Math.max(-maxDistance,y-midy));}};EightBittr.prototype.ensureCorrectCaller=function(current){if(!(current instanceof EightBittr)){throw new Error("A function requires the caller ('this') to be the "
+"manipulated EightBittr object. Unfortunately, 'this' is a "
+typeof(this)+".");}
return current;};EightBittr.prototype.proliferate=function(recipient,donor,noOverride){if(noOverride===void 0){noOverride=false;}
var setting,i;for(i in donor){if(donor.hasOwnProperty(i)){if(noOverride&&recipient.hasOwnProperty(i)){continue;}
setting=donor[i];if(typeof setting==="object"){if(!recipient.hasOwnProperty(i)){recipient[i]=new setting.constructor();}
this.proliferate(recipient[i],setting,noOverride);}
else{recipient[i]=setting;}}}
return recipient;};EightBittr.prototype.proliferateHard=function(recipient,donor,noOverride){var setting,i;for(i in donor){if(donor.hasOwnProperty(i)){if(noOverride&&recipient[i]){continue;}
setting=donor[i];if(typeof setting==="object"){if(!recipient[i]){recipient[i]=new setting.constructor();}
this.proliferate(recipient[i],setting,noOverride);}
else{recipient[i]=setting;}}}
return recipient;};EightBittr.prototype.proliferateElement=function(recipient,donor,noOverride){if(noOverride===void 0){noOverride=false;}
var setting,i,j;for(i in donor){if(donor.hasOwnProperty(i)){if(noOverride&&recipient.hasOwnProperty(i)){continue;}
setting=donor[i];switch(i){case "children":case "children":if(typeof(setting)!=="undefined"){for(j=0;j<setting.length;j+=1){recipient.appendChild(setting[j]);}}
break;case "style":this.proliferate(recipient[i],setting);break;default:if(setting===null){recipient[i]=null;}
else if(typeof setting==="object"){if(!recipient.hasOwnProperty(i)){recipient[i]=new setting.constructor();}
this.proliferate(recipient[i],setting,noOverride);}
else{recipient[i]=setting;}
break;}}}
return recipient;};EightBittr.prototype.createElement=function(tag){var args=[];for(var _i=1;_i<arguments.length;_i++){args[_i-1]=arguments[_i];}
var EightBitter=EightBittr.prototype.ensureCorrectCaller(this),element=document.createElement(tag||"div"),i;for(i=0;i<args.length;i+=1){EightBitter.proliferateElement(element,args[i]);}
return element;};EightBittr.prototype.followPathHard=function(object,path,index){if(index===void 0){index=0;}
for(var i=index;i<path.length;i+=1){if(typeof object[path[i]]==="undefined"){return undefined;}
else{object=object[path[i]];}}
return object;};EightBittr.prototype.arraySwitch=function(object,arrayOld,arrayNew){arrayOld.splice(arrayOld.indexOf(object),1);arrayNew.push(object);};EightBittr.prototype.arrayToBeginning=function(object,array){array.splice(array.indexOf(object),1);array.unshift(object);};EightBittr.prototype.arrayToEnd=function(object,array){array.splice(array.indexOf(object),1);array.push(object);};EightBittr.prototype.arrayToIndex=function(object,array,index){array.splice(array.indexOf(object),1);array.splice(index,0,object);};return EightBittr;})();EightBittr_1.EightBittr=EightBittr;;})(EightBittr||(EightBittr={}));