var GamesRunnr;(function(GamesRunnr_1){"use strict";var GamesRunnr=(function(){function GamesRunnr(settings){var i;if(typeof settings.games==="undefined"){throw new Error("No games given to GamesRunnr.");}
this.games=settings.games;this.interval=settings.interval||1000/60;this.speed=settings.speed||1;this.onPause=settings.onPause;this.onPlay=settings.onPlay;this.callbackArguments=settings.callbackArguments||[this];this.adjustFramerate=settings.adjustFramerate;this.FPSAnalyzer=settings.FPSAnalyzer||new FPSAnalyzr.FPSAnalyzr(settings.FPSAnalyzerSettings);this.scope=settings.scope||this;this.paused=true;this.upkeepScheduler=settings.upkeepScheduler||function(handler,timeout){return setTimeout(handler,timeout);};this.upkeepCanceller=settings.upkeepCanceller||function(handle){clearTimeout(handle);};this.upkeepBound=this.upkeep.bind(this);for(i=0;i<this.games.length;i+=1){this.games[i]=this.games[i].bind(this.scope);}
this.setIntervalReal();}
GamesRunnr.prototype.getFPSAnalyzer=function(){return this.FPSAnalyzer;};GamesRunnr.prototype.getPaused=function(){return this.paused;};GamesRunnr.prototype.getGames=function(){return this.games;};GamesRunnr.prototype.getInterval=function(){return this.interval;};GamesRunnr.prototype.getSpeed=function(){return this.speed;};GamesRunnr.prototype.getOnPause=function(){return this.onPause;};GamesRunnr.prototype.getOnPlay=function(){return this.onPlay;};GamesRunnr.prototype.getCallbackArguments=function(){return this.callbackArguments;};GamesRunnr.prototype.getUpkeepScheduler=function(){return this.upkeepScheduler;};GamesRunnr.prototype.getUpkeepCanceller=function(){return this.upkeepCanceller;};GamesRunnr.prototype.upkeep=function(){if(this.paused){return;}
this.upkeepCanceller(this.upkeepNext);if(this.adjustFramerate){this.upkeepNext=this.upkeepScheduler(this.upkeepBound,this.intervalReal-(this.upkeepTimed()|0));}
else{this.upkeepNext=this.upkeepScheduler(this.upkeepBound,this.intervalReal);this.games.forEach(this.run);}
if(this.FPSAnalyzer){this.FPSAnalyzer.measure();}};GamesRunnr.prototype.upkeepTimed=function(){if(!this.FPSAnalyzer){throw new Error("An internal FPSAnalyzr is required for upkeepTimed.");}
var now=this.FPSAnalyzer.getTimestamp();this.games.forEach(this.run);return this.FPSAnalyzer.getTimestamp()-now;};GamesRunnr.prototype.play=function(){if(!this.paused){return;}
this.paused=false;if(this.onPlay){this.onPlay.apply(this,this.callbackArguments);}
this.upkeep();};GamesRunnr.prototype.pause=function(){if(this.paused){return;}
this.paused=true;if(this.onPause){this.onPause.apply(this,this.callbackArguments);}
this.upkeepCanceller(this.upkeepNext);};GamesRunnr.prototype.step=function(times){if(times===void 0){times=1;}
this.play();this.pause();if(times>0){this.step(times-1);}};GamesRunnr.prototype.togglePause=function(){this.paused?this.play():this.pause();};GamesRunnr.prototype.setInterval=function(interval){var intervalReal=Number(interval);if(isNaN(intervalReal)){throw new Error("Invalid interval given to setInterval: "+interval);}
this.interval=intervalReal;this.setIntervalReal();};GamesRunnr.prototype.setSpeed=function(speed){var speedReal=Number(speed);if(isNaN(speedReal)){throw new Error("Invalid speed given to setSpeed: "+speed);}
this.speed=speedReal;this.setIntervalReal();};GamesRunnr.prototype.setIntervalReal=function(){this.intervalReal=(1/this.speed)*this.interval;};GamesRunnr.prototype.run=function(game){game();};return GamesRunnr;})();GamesRunnr_1.GamesRunnr=GamesRunnr;})(GamesRunnr||(GamesRunnr={}));