var InputWritr;(function(InputWritr_1){"use strict";var InputWritr=(function(){function InputWritr(settings){if(!settings.triggers){throw new Error("No triggers given to InputWritr.");}
this.triggers=settings.triggers;if(typeof settings.getTimestamp==="undefined"){if(typeof performance==="undefined"){this.getTimestamp=function(){return Date.now();};}
else{this.getTimestamp=(performance.now||performance.webkitNow||performance.mozNow||performance.msNow||performance.oNow).bind(performance);}}
else{this.getTimestamp=settings.getTimestamp;}
this.eventInformation=settings.eventInformation;this.canTrigger=settings.hasOwnProperty("canTrigger")?settings.canTrigger:function(){return true;};this.isRecording=settings.hasOwnProperty("isRecording")?settings.isRecording:function(){return true;};this.history={};this.histories={"length":0};this.aliases={};this.addAliases(settings.aliases||{});this.keyAliasesToCodes=settings.keyAliasesToCodes||{"shift":16,"ctrl":17,"space":32,"left":37,"up":38,"right":39,"down":40};this.keyCodesToAliases=settings.keyCodesToAliases||{"16":"shift","17":"ctrl","32":"space","37":"left","38":"up","39":"right","40":"down"};}
InputWritr.prototype.restartHistory=function(keepHistory){if(keepHistory===void 0){keepHistory=true;}
if(keepHistory){this.saveHistory(this.history);}
this.history={};this.startingTime=this.getTimestamp();};InputWritr.prototype.getAliases=function(){return this.aliases;};InputWritr.prototype.getAliasesAsKeyStrings=function(){var output={},alias;for(alias in this.aliases){if(this.aliases.hasOwnProperty(alias)){output[alias]=this.getAliasAsKeyStrings(alias);}}
return output;};InputWritr.prototype.getAliasAsKeyStrings=function(alias){return this.aliases[alias].map(this.convertAliasToKeyString.bind(this));};InputWritr.prototype.convertAliasToKeyString=function(alias){if(alias.constructor===String){return alias;}
if(alias>96&&alias<105){return String.fromCharCode(alias-48);}
if(alias>64&&alias<97){return String.fromCharCode(alias);}
return typeof this.keyCodesToAliases[alias]!=="undefined"?this.keyCodesToAliases[alias]:"?";};InputWritr.prototype.convertKeyStringToAlias=function(key){if(key.constructor===Number){return key;}
if(key.length===1){return key.charCodeAt(0)-32;}
return typeof this.keyAliasesToCodes[key]!=="undefined"?this.keyAliasesToCodes[key]:-1;};InputWritr.prototype.getHistory=function(name){if(name===void 0){name=undefined;}
return arguments.length?this.histories[name]:history;};InputWritr.prototype.getHistories=function(){return this.histories;};InputWritr.prototype.getCanTrigger=function(){return this.canTrigger;};InputWritr.prototype.getIsRecording=function(){return this.isRecording;};InputWritr.prototype.setCanTrigger=function(canTriggerNew){if(canTriggerNew.constructor===Boolean){this.canTrigger=function(){return canTriggerNew;};}
else{this.canTrigger=canTriggerNew;}};InputWritr.prototype.setIsRecording=function(isRecordingNew){if(isRecordingNew.constructor===Boolean){this.isRecording=function(){return isRecordingNew;};}
else{this.isRecording=isRecordingNew;}};InputWritr.prototype.setEventInformation=function(eventInformationNew){this.eventInformation=eventInformationNew;};InputWritr.prototype.addAliasValues=function(name,values){var triggerName,triggerGroup,i;if(!this.aliases.hasOwnProperty(name)){this.aliases[name]=values;}
else{this.aliases[name].push.apply(this.aliases[name],values);}
for(triggerName in this.triggers){if(this.triggers.hasOwnProperty(triggerName)){triggerGroup=this.triggers[triggerName];if(triggerGroup.hasOwnProperty(name)){for(i=0;i<values.length;i+=1){triggerGroup[values[i]]=triggerGroup[name];}}}}};InputWritr.prototype.removeAliasValues=function(name,values){var triggerName,triggerGroup,i;if(!this.aliases.hasOwnProperty(name)){return;}
for(i=0;i<values.length;i+=1){this.aliases[name].splice(this.aliases[name].indexOf(values[i],1));}
for(triggerName in this.triggers){if(this.triggers.hasOwnProperty(triggerName)){triggerGroup=this.triggers[triggerName];if(triggerGroup.hasOwnProperty(name)){for(i=0;i<values.length;i+=1){if(triggerGroup.hasOwnProperty(values[i])){delete triggerGroup[values[i]];}}}}}};InputWritr.prototype.switchAliasValues=function(name,valuesOld,valuesNew){this.removeAliasValues(name,valuesOld);this.addAliasValues(name,valuesNew);};InputWritr.prototype.addAliases=function(aliasesRaw){var aliasName;for(aliasName in aliasesRaw){if(aliasesRaw.hasOwnProperty(aliasName)){this.addAliasValues(aliasName,aliasesRaw[aliasName]);}}};InputWritr.prototype.addEvent=function(trigger,label,callback){var i;if(!this.triggers.hasOwnProperty(trigger)){throw new Error("Unknown trigger requested: '"+trigger+"'.");}
this.triggers[trigger][label]=callback;if(this.aliases.hasOwnProperty(label)){for(i=0;i<this.aliases[label].length;i+=1){this.triggers[trigger][this.aliases[label][i]]=callback;}}};InputWritr.prototype.removeEvent=function(trigger,label){var i;if(!this.triggers.hasOwnProperty(trigger)){throw new Error("Unknown trigger requested: '"+trigger+"'.");}
delete this.triggers[trigger][label];if(this.aliases.hasOwnProperty(label)){for(i=0;i<this.aliases[label].length;i+=1){if(this.triggers[trigger][this.aliases[label][i]]){delete this.triggers[trigger][this.aliases[label][i]];}}}};InputWritr.prototype.saveHistory=function(name){if(name===void 0){name=undefined;}
this.histories[this.histories.length]=history;this.histories.length+=1;if(arguments.length){this.histories[name]=history;}};InputWritr.prototype.playHistory=function(){this.playEvents(this.history);};InputWritr.prototype.playEvents=function(events){var timeouts={},time,call;for(time in events){if(events.hasOwnProperty(time)){call=this.makeEventCall(events[time]);timeouts[time]=setTimeout(call,(Number(time)-this.startingTime)|0);}}};InputWritr.prototype.callEvent=function(event,keyCode,sourceEvent){if(!this.canTrigger(event,keyCode)){return;}
if(!event){throw new Error("Blank event given, ignoring it.");}
if(event.constructor===String){event=this.triggers[event][keyCode];}
return event(this.eventInformation,sourceEvent);};InputWritr.prototype.makePipe=function(trigger,codeLabel,preventDefaults){var functions=this.triggers[trigger],InputWriter=this;if(!functions){throw new Error("No trigger of label '"+trigger+"' defined.");}
return function Pipe(event){var alias=event[codeLabel];if(preventDefaults&&event.preventDefault instanceof Function){event.preventDefault();}
if(functions.hasOwnProperty(alias)){if(InputWriter.isRecording()){InputWriter.history[InputWriter.getTimestamp()|0]=[trigger,alias];}
InputWriter.callEvent(functions[alias],alias,event);}};};InputWritr.prototype.makeEventCall=function(info){return function(){this.callEvent(info[0],info[1]);};};return InputWritr;})();InputWritr_1.InputWritr=InputWritr;})(InputWritr||(InputWritr={}));