var MapsCreatr;(function(MapsCreatr_1){"use strict";var PreThing=(function(){function PreThing(thing,reference,ObjectMaker){this.thing=thing;this.title=thing.title;this.reference=reference;this.spawned=false;this.left=reference.x||0;this.top=reference.y||0;this.right=this.left+(reference.width||ObjectMaker.getFullPropertiesOf(this.title).width);this.bottom=this.top+(reference.height||ObjectMaker.getFullPropertiesOf(this.title).height);if(reference.position){this.position=reference.position;}}
return PreThing;})();MapsCreatr_1.PreThing=PreThing;var MapsCreatr=(function(){function MapsCreatr(settings){if(!settings){throw new Error("No settings given to MapsCreatr.");}
if(!settings.ObjectMaker){throw new Error("No ObjectMakr given to MapsCreatr.");}
this.ObjectMaker=settings.ObjectMaker;if(typeof this.ObjectMaker.getFullProperties()==="undefined"){throw new Error("MapsCreatr's ObjectMaker must store full properties.");}
if(!settings.groupTypes){throw new Error("No groupTypes given to MapsCreatr.");}
this.groupTypes=settings.groupTypes;this.keyGroupType=settings.keyGroupType||"groupType";this.keyEntrance=settings.keyEntrance||"entrance";this.macros=settings.macros||{};this.scope=settings.scope||this;this.entrances=settings.entrances;this.requireEntrance=settings.requireEntrance;this.mapsRaw={};this.maps={};if(settings.maps){this.storeMaps(settings.maps);}}
MapsCreatr.prototype.getObjectMaker=function(){return this.ObjectMaker;};MapsCreatr.prototype.getGroupTypes=function(){return this.groupTypes;};MapsCreatr.prototype.getKeyGroupType=function(){return this.keyGroupType;};MapsCreatr.prototype.getKeyEntrance=function(){return this.keyEntrance;};MapsCreatr.prototype.getMacros=function(){return this.macros;};MapsCreatr.prototype.getScope=function(){return this.scope;};MapsCreatr.prototype.getRequireEntrance=function(){return this.requireEntrance;};MapsCreatr.prototype.getMapsRaw=function(){return this.mapsRaw;};MapsCreatr.prototype.getMaps=function(){return this.maps;};MapsCreatr.prototype.getMapRaw=function(name){var mapRaw=this.mapsRaw[name];if(!mapRaw){throw new Error("No map found under: "+name);}
return mapRaw;};MapsCreatr.prototype.getMap=function(name){var map=this.maps[name];if(!map){throw new Error("No map found under: "+name);}
if(!map.initialized){this.setMapAreas(map);this.setMapLocations(map);map.initialized=true;}
return map;};MapsCreatr.prototype.storeMaps=function(maps){var i;for(i in maps){if(maps.hasOwnProperty(i)){this.storeMap(i,maps[i]);}}};MapsCreatr.prototype.storeMap=function(name,mapRaw){if(!name){throw new Error("Maps cannot be created with no name.");}
var map=this.ObjectMaker.make("Map",mapRaw);this.mapsRaw[name]=mapRaw;if(!map.areas){throw new Error("Maps cannot be used with no areas: "+name);}
if(!map.locations){throw new Error("Maps cannot be used with no locations: "+name);}
this.maps[name]=map;return map;};MapsCreatr.prototype.getPreThings=function(area){var map=area.map,creation=area.creation,prethings=this.fromKeys(this.groupTypes),i;area.collections={};for(i=0;i<creation.length;i+=1){this.analyzePreSwitch(creation[i],prethings,area,map);}
return this.processPreThingsArrays(prethings);};MapsCreatr.prototype.analyzePreSwitch=function(reference,prethings,area,map){if(reference.macro){return this.analyzePreMacro(reference,prethings,area,map);}
else{return this.analyzePreThing(reference,prethings,area,map);}};MapsCreatr.prototype.analyzePreMacro=function(reference,prethings,area,map){var macro=this.macros[reference.macro],outputs,i;if(!macro){console.warn("A non-existent macro is referenced. It will be ignored:",macro,reference,prethings,area,map);return;}
outputs=macro(reference,prethings,area,map,this.scope);if(outputs){if(outputs instanceof Array){for(i=0;i<outputs.length;i+=1){this.analyzePreSwitch(outputs[i],prethings,area,map);}}
else{this.analyzePreSwitch(outputs,prethings,area,map);}}
return outputs;};MapsCreatr.prototype.analyzePreThing=function(reference,prethings,area,map){var title=reference.thing,thing,prething;if(!this.ObjectMaker.hasFunction(title)){console.warn("A non-existent Thing type is referenced. It will be ignored:",title,reference,prethings,area,map);return;}
prething=new PreThing(this.ObjectMaker.make(title,reference),reference,this.ObjectMaker);thing=prething.thing;if(!prething.thing[this.keyGroupType]){console.warn("A Thing does not contain a "+this.keyGroupType+". It will be ignored:",prething,"\n",arguments);return;}
if(this.groupTypes.indexOf(prething.thing[this.keyGroupType])===-1){console.warn("A Thing contains an unknown "+this.keyGroupType+". It will be ignored:",thing[this.keyGroupType],prething,reference,prethings,area,map);return;}
prethings[prething.thing[this.keyGroupType]].push(prething);if(!thing.noBoundaryStretch&&area.boundaries){this.stretchAreaBoundaries(prething,area);}
if(thing[this.keyEntrance]!==undefined&&typeof thing[this.keyEntrance]!=="object"){if(typeof map.locations[thing[this.keyEntrance]]!=="undefined"){if(typeof map.locations[thing[this.keyEntrance]].xloc==="undefined"){map.locations[thing[this.keyEntrance]].xloc=prething.left;}
if(typeof map.locations[thing[this.keyEntrance]].yloc==="undefined"){map.locations[thing[this.keyEntrance]].yloc=prething.top;}
map.locations[thing[this.keyEntrance]].entrance=prething.thing;}}
if(reference.collectionName&&area.collections){this.ensureThingCollection(prething,reference.collectionName,reference.collectionKey,area);}
return prething;};MapsCreatr.prototype.setMapAreas=function(map){var areasRaw=map.areas,locationsRaw=map.locations,areasParsed=new areasRaw.constructor(),locationsParsed=new locationsRaw.constructor(),area,location,i;for(i in areasRaw){if(areasRaw.hasOwnProperty(i)){area=this.ObjectMaker.make("Area",areasRaw[i]);areasParsed[i]=area;area.map=map;area.name=i;area.boundaries={"top":0,"right":0,"bottom":0,"left":0};}}
for(i in locationsRaw){if(locationsRaw.hasOwnProperty(i)){location=this.ObjectMaker.make("Location",locationsRaw[i]);locationsParsed[i]=location;location.entryRaw=locationsRaw[i].entry;location.name=i;location.area=locationsRaw[i].area||0;if(this.requireEntrance){if(!this.entrances.hasOwnProperty(location.entryRaw)){throw new Error("Location "+i+" has unknown entry string: "+location.entryRaw);}}
if(this.entrances&&location.entryRaw){location.entry=this.entrances[location.entryRaw];}
else if(location.entry&&location.entry.constructor===String){location.entry=this.entrances[String(location.entry)];}}}
map.areas=areasParsed;map.locations=locationsParsed;};MapsCreatr.prototype.setMapLocations=function(map){var locsRaw=map.locations,locsParsed=new locsRaw.constructor(),location,i;for(i in locsRaw){if(locsRaw.hasOwnProperty(i)){location=this.ObjectMaker.make("Location",locsRaw[i]);locsParsed[i]=location;location.area=map.areas[locsRaw[i].area||0];if(!locsParsed[i].area){throw new Error("Location "+i+" references an invalid area:"+locsRaw[i].area);}}}
map.locations=locsParsed;};MapsCreatr.prototype.stretchAreaBoundaries=function(prething,area){var boundaries=area.boundaries;boundaries.top=Math.min(prething.top,boundaries.top);boundaries.right=Math.max(prething.right,boundaries.right);boundaries.bottom=Math.max(prething.bottom,boundaries.bottom);boundaries.left=Math.min(prething.left,boundaries.left);};MapsCreatr.prototype.ensureThingCollection=function(prething,collectionName,collectionKey,area){var thing=prething.thing,collection=area.collections[collectionName];if(!collection){collection=area.collections[collectionName]={};}
thing.collection=collection;collection[collectionKey]=thing;};MapsCreatr.prototype.processPreThingsArrays=function(prethings){var scope=this,output={},i;for(i in prethings){if(prethings.hasOwnProperty(i)){var children=prethings[i],array={"xInc":this.getArraySorted(children,this.sortPreThingsXInc),"xDec":this.getArraySorted(children,this.sortPreThingsXDec),"yInc":this.getArraySorted(children,this.sortPreThingsYInc),"yDec":this.getArraySorted(children,this.sortPreThingsYDec)};array.push=(function(prething){scope.addArraySorted(this.xInc,prething,scope.sortPreThingsXInc);scope.addArraySorted(this.xDec,prething,scope.sortPreThingsXDec);scope.addArraySorted(this.yInc,prething,scope.sortPreThingsYInc);scope.addArraySorted(this.yDec,prething,scope.sortPreThingsYDec);}).bind(array);output[i]=array;}}
return output;};MapsCreatr.prototype.fromKeys=function(arr){var output={},i;for(i=0;i<arr.length;i+=1){output[arr[i]]=[];}
return output;};MapsCreatr.prototype.getArraySorted=function(array,sorter){var copy=array.slice();copy.sort(sorter);return copy;};MapsCreatr.prototype.addArraySorted=function(array,element,sorter){var lower=0,upper=array.length,index;while(lower!==upper){index=((lower+upper)/2)|0;if(sorter(element,array[index])<0){upper=index;}
else{lower=index+1;}}
if(lower===upper){array.splice(lower,0,element);return;}};MapsCreatr.prototype.sortPreThingsXInc=function(a,b){return a.left===b.left?a.top-b.top:a.left-b.left;};MapsCreatr.prototype.sortPreThingsXDec=function(a,b){return b.right===a.right?b.bottom-a.bottom:b.right-a.right;};MapsCreatr.prototype.sortPreThingsYInc=function(a,b){return a.top===b.top?a.left-b.left:a.top-b.top;};MapsCreatr.prototype.sortPreThingsYDec=function(a,b){return b.bottom===a.bottom?b.right-a.right:b.bottom-a.bottom;};return MapsCreatr;})();MapsCreatr_1.MapsCreatr=MapsCreatr;})(MapsCreatr||(MapsCreatr={}));