var ScenePlayr;(function(ScenePlayr_1){"use strict";var ScenePlayr=(function(){function ScenePlayr(settings){if(settings===void 0){settings={};}
this.cutscenes=settings.cutscenes||{};this.cutsceneArguments=settings.cutsceneArguments||[];}
ScenePlayr.prototype.getCutscenes=function(){return this.cutscenes;};ScenePlayr.prototype.getCutscene=function(){return this.cutscene;};ScenePlayr.prototype.getOtherCutscene=function(name){return this.cutscenes[name];};ScenePlayr.prototype.getRoutine=function(){return this.routine;};ScenePlayr.prototype.getOtherRoutine=function(name){return this.cutscene.routines[name];};ScenePlayr.prototype.getCutsceneName=function(){return this.cutsceneName;};ScenePlayr.prototype.getCutsceneSettings=function(){return this.cutsceneSettings;};ScenePlayr.prototype.addCutsceneSetting=function(key,value){this.cutsceneSettings[key]=value;};ScenePlayr.prototype.startCutscene=function(name,settings){if(settings===void 0){settings={};}
if(!name){throw new Error("No name given to ScenePlayr.playScene.");}
if(this.cutsceneName){this.stopCutscene();}
this.cutscene=this.cutscenes[name];this.cutsceneName=name;this.cutsceneSettings=settings||{};this.cutsceneSettings.cutscene=this.cutscene;this.cutsceneSettings.cutsceneName=name;this.cutsceneArguments.push(this.cutsceneSettings);if(this.cutscene.firstRoutine){this.playRoutine(this.cutscene.firstRoutine);}};ScenePlayr.prototype.bindCutscene=function(name){var args=[];for(var _i=1;_i<arguments.length;_i++){args[_i-1]=arguments[_i];}
return this.startCutscene.bind(self,name,args);};ScenePlayr.prototype.stopCutscene=function(){this.cutscene=undefined;this.cutsceneName=undefined;this.cutsceneSettings=undefined;this.routine=undefined;this.cutsceneArguments.pop();};ScenePlayr.prototype.playRoutine=function(name){var args=[];for(var _i=1;_i<arguments.length;_i++){args[_i-1]=arguments[_i];}
if(!this.cutscene){throw new Error("No cutscene is currently playing.");}
if(!this.cutscene.routines[name]){throw new Error("The "+this.cutsceneName+" cutscene does not contain a "+name+" routine.");}
this.routine=this.cutscene.routines[name];this.cutsceneSettings.routine=this.routine;this.cutsceneSettings.routineName=name;this.cutsceneSettings.routineArguments=args;this.routine.apply(this,this.cutsceneArguments);};ScenePlayr.prototype.bindRoutine=function(name){var args=[];for(var _i=1;_i<arguments.length;_i++){args[_i-1]=arguments[_i];}
return this.playRoutine.bind(this,name,args);};return ScenePlayr;})();ScenePlayr_1.ScenePlayr=ScenePlayr;})(ScenePlayr||(ScenePlayr={}));