var ThingHittr;(function(ThingHittr_1){"use strict";var ThingHittr=(function(){function ThingHittr(settings){this.globalCheckGenerators=settings.globalCheckGenerators;this.hitCheckGenerators=settings.hitCheckGenerators;this.hitFunctionGenerators=settings.hitFunctionGenerators;this.groupNames=settings.groupNames;this.keyNumQuads=settings.keyNumQuads||"numquads";this.keyQuadrants=settings.keyQuadrants||"quadrants";this.keyGroupName=settings.keyGroupName||"group";this.hitChecks={};this.globalChecks={};this.hitFunctions={};this.cachedGroupNames={};this.cachedTypeNames={};this.checkHitsOf={};}
ThingHittr.prototype.cacheHitCheckGroup=function(groupName){if(this.cachedGroupNames[groupName]){return;}
this.cachedGroupNames[groupName]=true;if(typeof this.globalCheckGenerators[groupName]!=="undefined"){this.globalChecks[groupName]=this.cacheGlobalCheck(groupName);}};ThingHittr.prototype.cacheHitCheckType=function(typeName,groupName){if(this.cachedTypeNames[typeName]){return;}
if(typeof this.globalCheckGenerators[groupName]!=="undefined"){this.globalChecks[typeName]=this.cacheGlobalCheck(groupName);}
if(typeof this.hitCheckGenerators[groupName]!=="undefined"){this.hitChecks[typeName]=this.cacheFunctionGroup(this.hitCheckGenerators[groupName]);}
if(typeof this.hitFunctionGenerators[groupName]!=="undefined"){this.hitFunctions[typeName]=this.cacheFunctionGroup(this.hitFunctionGenerators[groupName]);}
this.cachedTypeNames[typeName]=true;this.checkHitsOf[typeName]=this.generateHitsCheck(typeName).bind(this);};ThingHittr.prototype.generateHitsCheck=function(typeName){return function checkHitsOf(thing){var others,other,hitCheck,i,j,k;if(typeof this.globalChecks[this.typeName]!=="undefined"&&!this.globalChecks[this.typeName](thing)){return;}
for(i=0;i<thing[this.keyNumQuads];i+=1){for(j=0;j<this.groupNames.length;j+=1){hitCheck=this.hitChecks[typeName][this.groupNames[j]];if(!hitCheck){continue;}
others=thing[this.keyQuadrants][i].things[this.groupNames[j]];for(k=0;k<others.length;k+=1){other=others[k];if(thing===other){break;}
if(typeof this.globalChecks[other[this.keyGroupName]]!=="undefined"&&!this.globalChecks[other[this.keyGroupName]](other)){continue;}
if(hitCheck(thing,other)){this.hitFunctions[typeName][other[this.keyGroupName]](thing,other);}}}}};};ThingHittr.prototype.checkHit=function(thing,other,thingType,otherGroup){var checks=this.hitChecks[thingType],check;if(!checks){throw new Error("No hit checks defined for "+thingType+".");}
check=checks[otherGroup];if(!check){throw new Error("No hit check defined for "+thingType+" and "+otherGroup+".");}
return check(thing,other);};ThingHittr.prototype.cacheGlobalCheck=function(groupName){return this.globalCheckGenerators[groupName]();};ThingHittr.prototype.cacheFunctionGroup=function(functions){var output={},i;for(i in functions){if(functions.hasOwnProperty(i)){output[i]=functions[i]();}}
return output;};return ThingHittr;})();ThingHittr_1.ThingHittr=ThingHittr;})(ThingHittr||(ThingHittr={}));