var TimeHandlr;(function(TimeHandlr_1){"use strict";var TimeHandlr=(function(){function TimeHandlr(settings){this.time=0;this.events={};this.timingDefault=settings.timingDefault||1;this.keyCycles=settings.keyCycles||"cycles";this.keyClassName=settings.keyClassName||"className";this.keyOnClassCycleStart=settings.keyOnClassCycleStart||"onClassCycleStart";this.keyDoClassCycleStart=settings.keyDoClassCycleStart||"doClassCycleStart";this.keyCycleCheckValidity=settings.keyCycleCheckValidity;this.copyCycleSettings=typeof settings.copyCycleSettings==="undefined"?true:settings.copyCycleSettings;this.classAdd=settings.classAdd||this.classAddGeneric;this.classRemove=settings.classRemove||this.classRemoveGeneric;}
TimeHandlr.prototype.getTime=function(){return this.time;};TimeHandlr.prototype.getEvents=function(){return this.events;};TimeHandlr.prototype.addEvent=function(callback,timeDelay){if(timeDelay===void 0){timeDelay=1;}
var args=[];for(var _i=2;_i<arguments.length;_i++){args[_i-2]=arguments[_i];}
var event;if(typeof callback!=="function"){throw new Error("Invalid event given to addEvent.");}
timeDelay=timeDelay||1;event=this.createEvent(callback,this.time+timeDelay,timeDelay,args,1);this.insertEvent(event,event.timeDelay);return event;};TimeHandlr.prototype.addEventInterval=function(callback,timeDelay,numRepeats){if(timeDelay===void 0){timeDelay=1;}
if(numRepeats===void 0){numRepeats=1;}
var args=[];for(var _i=3;_i<arguments.length;_i++){args[_i-3]=arguments[_i];}
var event,argsParsed;if(typeof callback!=="function"){throw new Error("Invalid event given to addEventInterval.");}
timeDelay=timeDelay||1;numRepeats=numRepeats||1;argsParsed=Array.prototype.slice.call(arguments,3);event=this.createEvent(callback,this.time+timeDelay,timeDelay,argsParsed,numRepeats);callback.event=event;this.insertEvent(event,event.timeDelay);return event;};TimeHandlr.prototype.addEventIntervalSynched=function(callback,timeDelay,numRepeats,thing,settings){var calcTime=timeDelay*settings.length,entryTime=Math.ceil(this.time/calcTime)*calcTime,scope=this,args=Array.prototype.slice.call(arguments),adder=Function.apply.bind(this.addEventInterval,scope,args);timeDelay=timeDelay||1;numRepeats=numRepeats||1;if(entryTime===this.time){return adder();}
this.addEvent(adder,entryTime-this.time,scope,args,thing);};TimeHandlr.prototype.handleEvents=function(){var currentEvents,event,length,i;this.time+=1;currentEvents=this.events[this.time];if(!currentEvents){return;}
for(i=0,length=currentEvents.length;i<length;++i){event=currentEvents[i];if(event.repeat>0&&!event.callback.apply(this,event.args)){if(event.count_changer){event.count_changer(event);}
if(event.repeat.constructor===Function){if(event.repeat.call(event)){event.count+=event.timeRepeat;this.insertEvent(event,event.timeDelay);}}
else{event.repeat=event.repeat-1;if(event.repeat>0){event.timeDelay+=event.timeRepeat;this.insertEvent(event,event.timeDelay);}}}}
delete this.events[this.time];};TimeHandlr.prototype.cancelEvent=function(event){event.repeat=0;};TimeHandlr.prototype.cancelAllEvents=function(){this.events={};};TimeHandlr.prototype.cancelClassCycle=function(thing,name){var cycle;if(!thing[this.keyCycles]||!thing[this.keyCycles][name]){return;}
cycle=thing[this.keyCycles][name];cycle.length=1;cycle[0]=false;delete thing[this.keyCycles][name];};TimeHandlr.prototype.cancelAllCycles=function(thing){var keyCycles=thing[this.keyCycles],cycle,name;for(name in keyCycles){if(!keyCycles.hasOwnProperty(name)){continue;}
cycle=keyCycles[name];cycle.length=1;cycle[0]=false;delete keyCycles[name];}};TimeHandlr.prototype.addClassCycle=function(thing,settings,name,timing){var isTimingFunction=typeof timing==="function",cycle;if(!thing[this.keyCycles]){thing[this.keyCycles]={};}
this.cancelClassCycle(thing,name);name=name||"0";cycle=thing[this.keyCycles][name]=this.setClassCycle(thing,settings,isTimingFunction?0:timing);if(cycle.event&&isTimingFunction){cycle.event.count_changer=timing;}
this.cycleClass(thing,settings);return cycle;};TimeHandlr.prototype.addClassCycleSynched=function(thing,settings,name,timing){var cycle;if(!thing[this.keyCycles]){thing[this.keyCycles]={};}
this.cancelClassCycle(thing,name);name=name||"0";cycle=thing[this.keyCycles][name]=this.setClassCycle(thing,settings,timing,true);this.cycleClass(thing,thing[this.keyCycles][name]);return cycle;};TimeHandlr.prototype.setClassCycle=function(thing,settings,timing,synched){if(synched===void 0){synched=false;}
var scope=this,callback;if(this.copyCycleSettings){settings=this.makeSettingsCopy(settings);}
settings.loc=settings.oldclass=-1;callback=synched?this.addEventIntervalSynched:this.addEventInterval;callback=callback.bind(scope);thing[this.keyOnClassCycleStart]=function(){callback(scope.cycleClass,timing||scope.timingDefault,Infinity,thing,settings);};if(thing[this.keyDoClassCycleStart]){thing[this.keyOnClassCycleStart]();}
return settings;};TimeHandlr.prototype.cycleClass=function(thing,settings){var current,name;if(!thing||!settings||!settings.length||(this.keyCycleCheckValidity&&!thing[this.keyCycleCheckValidity])){return true;}
if(settings.oldclass!==-1&&settings.oldclass!==""){this.classRemove(thing,settings.oldclass);}
settings.loc=(settings.loc+=1)%settings.length;current=settings[settings.loc];if(current){if(current.constructor===Function){name=current(thing,settings);}
else{name=current;}
if(typeof name==="string"){settings.oldclass=name;this.classAdd(thing,name);return false;}
else{return(name===false);}}
else{return(current===false);}};TimeHandlr.prototype.createEvent=function(callback,timeDelay,timeRepeat,args,repeat){return{"callback":callback,"timeDelay":timeDelay,"timeRepeat":timeRepeat,"args":args,"repeat":repeat,"count":0};};TimeHandlr.prototype.insertEvent=function(event,time){if(!this.events[time]){this.events[time]=[event];}
else{this.events[time].push(event);}
return this.events[time];};TimeHandlr.prototype.makeSettingsCopy=function(original){var output=new original.constructor(),i;for(i in original){if(original.hasOwnProperty(i)){output[i]=original[i];}}
return output;};TimeHandlr.prototype.classAddGeneric=function(element,str){element[this.keyClassName]+=" "+str;};TimeHandlr.prototype.classRemoveGeneric=function(element,str){element[this.keyClassName]=element[this.keyClassName].replace(str,"");};return TimeHandlr;})();TimeHandlr_1.TimeHandlr=TimeHandlr;})(TimeHandlr||(TimeHandlr={}));