var WorldSeedr;(function(WorldSeedr_1){"use strict";var WorldSeedr=(function(){function WorldSeedr(settings){this.directionOpposites={"top":"bottom","right":"left","bottom":"top","left":"right"};this.directionSizing={"top":"height","right":"width","bottom":"height","left":"width"};this.directionNames=["top","right","bottom","left"];this.sizingNames=["width","height"];if(typeof settings.possibilities==="undefined"){throw new Error("No possibilities given to WorldSeedr.");}
this.possibilities=settings.possibilities;this.random=settings.random||Math.random.bind(Math);this.onPlacement=settings.onPlacement||console.log.bind(console,"Got:");this.clearGeneratedCommands();}
WorldSeedr.prototype.getPossibilities=function(){return this.possibilities;};WorldSeedr.prototype.setPossibilities=function(possibilities){this.possibilities=possibilities;};WorldSeedr.prototype.getOnPlacement=function(){return this.onPlacement;};WorldSeedr.prototype.setOnPlacement=function(onPlacement){this.onPlacement=onPlacement;};WorldSeedr.prototype.clearGeneratedCommands=function(){this.generatedCommands=[];};WorldSeedr.prototype.runGeneratedCommands=function(){this.onPlacement(this.generatedCommands);};WorldSeedr.prototype.generate=function(name,command){var schema=this.possibilities[name];if(!schema){throw new Error("No possibility exists under '"+name+"'");}
if(!schema.contents){throw new Error("Possibility '"+name+"' has no possibile outcomes.");}
return this.generateChildren(schema,this.objectCopy(command));};WorldSeedr.prototype.generateFull=function(schema){var generated=this.generate(schema.title,schema),child,i;if(!generated||!generated.children){return;}
for(i=0;i<generated.children.length;i+=1){child=generated.children[i];switch(child.type){case "Known":this.generatedCommands.push(child);break;case "Random":this.generateFull(child);break;default:throw new Error("Unknown child type: "+child.type);}}};WorldSeedr.prototype.generateChildren=function(schema,position,direction){if(direction===void 0){direction=undefined;}
var contents=schema.contents,spacing=contents.spacing||0,objectMerged=this.objectMerge(schema,position),children;direction=contents.direction||direction;switch(contents.mode){case "Random":children=this.generateChildrenRandom(contents,objectMerged,direction,spacing);break;case "Certain":children=this.generateChildrenCertain(contents,objectMerged,direction,spacing);break;case "Repeat":children=this.generateChildrenRepeat(contents,objectMerged,direction,spacing);break;case "Multiple":children=this.generateChildrenMultiple(contents,objectMerged,direction,spacing);break;default:throw new Error("Unknown contents mode: "+contents.mode);}
return this.wrapChoicePositionExtremes(children);};WorldSeedr.prototype.generateChildrenCertain=function(contents,position,direction,spacing){var scope=this;return contents.children.map(function(choice){if(choice.type==="Final"){return scope.parseChoiceFinal(contents,choice,position,direction);}
var output=scope.parseChoice(choice,position,direction);if(output){if(output.type!=="Known"){output.contents=scope.generate(output.title,position);}
scope.shrinkPositionByChild(position,output,direction,spacing);}
return output;}).filter(function(child){return child!==undefined;});};WorldSeedr.prototype.generateChildrenRepeat=function(contents,position,direction,spacing){var choices=contents.children,children=[],choice,child,i=0;while(this.positionIsNotEmpty(position,direction)){choice=choices[i];if(choice.type==="Final"){child=this.parseChoiceFinal(contents,choice,position,direction);}
else{child=this.parseChoice(choice,position,direction);if(child){if(child.type!=="Known"){child.contents=this.generate(child.title,position);}}}
if(child&&this.choiceFitsPosition(child,position)){this.shrinkPositionByChild(position,child,direction,spacing);children.push(child);}
else{break;}
i+=1;if(i>=choices.length){i=0;}}
return children;};WorldSeedr.prototype.generateChildrenRandom=function(contents,position,direction,spacing){var children=[],child;while(this.positionIsNotEmpty(position,direction)){child=this.generateChild(contents,position,direction);if(!child){break;}
this.shrinkPositionByChild(position,child,direction,spacing);children.push(child);if(contents.limit&&children.length>contents.limit){return;}}
return children;};WorldSeedr.prototype.generateChildrenMultiple=function(contents,position,direction,spacing){var scope=this;return contents.children.map(function(choice){var output=scope.parseChoice(choice,scope.objectCopy(position),direction);if(direction){scope.movePositionBySpacing(position,direction,spacing);}
return output;});};WorldSeedr.prototype.generateChild=function(contents,position,direction){var choice=this.chooseAmongPosition(contents.children,position);if(!choice){return undefined;}
return this.parseChoice(choice,position,direction);};WorldSeedr.prototype.parseChoice=function(choice,position,direction){var title=choice.title,schema=this.possibilities[title],output={"title":title,"type":choice.type,"arguments":choice.arguments instanceof Array?(this.chooseAmong(choice.arguments)).values:choice.arguments,"width":undefined,"height":undefined,"top":undefined,"right":undefined,"bottom":undefined,"left":undefined};this.ensureSizingOnChoice(output,choice,schema);this.ensureDirectionBoundsOnChoice(output,position);output[direction]=output[this.directionOpposites[direction]]+output[this.directionSizing[direction]];switch(schema.contents.snap){case "top":output.bottom=output.top-output.height;break;case "right":output.left=output.right-output.width;break;case "bottom":output.top=output.bottom+output.height;break;case "left":output.right=output.left+output.width;break;default:break;}
if(choice.stretch){if(!output.arguments){output.arguments={};}
if(choice.stretch.width){output.left=position.left;output.right=position.right;output.width=output.right-output.left;output.arguments.width=output.width;}
if(choice.stretch.height){output.top=position.top;output.bottom=position.bottom;output.height=output.top-output.bottom;output.arguments.height=output.height;}}
this.copySchemaArguments(schema,choice,output);return output;};WorldSeedr.prototype.parseChoiceFinal=function(parent,choice,position,direction){var schema=this.possibilities[choice.source],output={"type":"Known","title":choice.title,"arguments":choice.arguments,"width":schema.width,"height":schema.height,"top":position.top,"right":position.right,"bottom":position.bottom,"left":position.left};this.copySchemaArguments(schema,choice,output);return output;};WorldSeedr.prototype.chooseAmong=function(choices){if(!choices.length){return undefined;}
if(choices.length===1){return choices[0];}
var choice=this.randomPercentage(),sum=0,i;for(i=0;i<choices.length;i+=1){sum+=choices[i].percent;if(sum>=choice){return choices[i];}}};WorldSeedr.prototype.chooseAmongPosition=function(choices,position){var width=position.right-position.left,height=position.top-position.bottom,scope=this;return this.chooseAmong(choices.filter(function(choice){return scope.choiceFits(scope.possibilities[choice.title],width,height);}));};WorldSeedr.prototype.choiceFits=function(choice,width,height){return choice.width<=width&&choice.height<=height;};WorldSeedr.prototype.choiceFitsPosition=function(choice,position){return this.choiceFits(choice,position.right-position.left,position.top-position.bottom);};WorldSeedr.prototype.randomPercentage=function(){return Math.floor(this.random()*100)+1;};WorldSeedr.prototype.randomBetween=function(min,max){return Math.floor(this.random()*(1+max-min))+min;};WorldSeedr.prototype.objectCopy=function(original){var output={},i;for(i in original){if(original.hasOwnProperty(i)){output[i]=original[i];}}
return output;};WorldSeedr.prototype.objectMerge=function(primary,secondary){var output=this.objectCopy(primary),i;for(i in secondary){if(secondary.hasOwnProperty(i)&&!output.hasOwnProperty(i)){output[i]=secondary[i];}}
return output;};WorldSeedr.prototype.positionIsNotEmpty=function(position,direction){if(direction==="right"||direction==="left"){return position.left<position.right;}
else{return position.top>position.bottom;}};WorldSeedr.prototype.shrinkPositionByChild=function(position,child,direction,spacing){switch(direction){case "top":position.bottom=child.top+this.parseSpacing(spacing);break;case "right":position.left=child.right+this.parseSpacing(spacing);break;case "bottom":position.top=child.bottom-this.parseSpacing(spacing);break;case "left":position.right=child.left-this.parseSpacing(spacing);break;default:break;}};WorldSeedr.prototype.movePositionBySpacing=function(position,direction,spacing){if(spacing===void 0){spacing=0;}
var space=this.parseSpacing(spacing);switch(direction){case "top":position.top+=space;position.bottom+=space;break;case "right":position.left+=space;position.right+=space;break;case "bottom":position.top-=space;position.bottom-=space;break;case "left":position.left-=space;position.right-=space;break;default:throw new Error("Unknown direction: "+direction);}};WorldSeedr.prototype.parseSpacing=function(spacing){if(!spacing){return 0;}
switch(spacing.constructor){case Array:if(spacing[0].constructor===Number){return this.parseSpacingObject(this.randomBetween(spacing[0],spacing[1]));}
return this.parseSpacingObject(this.chooseAmong(spacing).value);case Object:return this.parseSpacingObject(spacing);default:return spacing;}};WorldSeedr.prototype.parseSpacingObject=function(spacing){if(spacing.constructor===Number){return spacing;}
var min=spacing.min,max=spacing.max,units=spacing.units||1;return this.randomBetween(min/units,max/units)*units;};WorldSeedr.prototype.wrapChoicePositionExtremes=function(children){var position,child,i;if(!children||!children.length){return undefined;}
child=children[0];position={"title":undefined,"top":child.top,"right":child.right,"bottom":child.bottom,"left":child.left,"width":undefined,"height":undefined,"children":children};if(children.length===1){return position;}
for(i=1;i<children.length;i+=1){child=children[i];if(!Object.keys(child).length){return position;}
position.top=Math.max(position.top,child.top);position.right=Math.max(position.right,child.right);position.bottom=Math.min(position.bottom,child.bottom);position.left=Math.min(position.left,child.left);}
position.width=position.right-position.left;position.height=position.top-position.bottom;return position;};WorldSeedr.prototype.copySchemaArguments=function(schema,choice,output){var map=schema.contents.argumentMap,i;if(!map){return;}
if(!output.arguments){output.arguments={};}
for(i in map){if(map.hasOwnProperty(i)){output.arguments[map[i]]=choice[i];}}};WorldSeedr.prototype.ensureSizingOnChoice=function(output,choice,schema){var name,i;for(i in this.sizingNames){if(!this.sizingNames.hasOwnProperty(i)){continue;}
name=this.sizingNames[i];output[name]=(choice.sizing&&typeof choice.sizing[name]!=="undefined")?choice.sizing[name]:schema[name];}};WorldSeedr.prototype.ensureDirectionBoundsOnChoice=function(output,position){var i;for(i in this.directionNames){if(this.directionNames.hasOwnProperty(i)){output[this.directionNames[i]]=position[this.directionNames[i]];}}};return WorldSeedr;})();WorldSeedr_1.WorldSeedr=WorldSeedr;})(WorldSeedr||(WorldSeedr={}));